project:
  type: website

website:
  title: "harp Dublin 2024"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - agenda.qmd
      - text: "Lessons"
        menu:
          - get-started.qmd
          - read-forecast.qmd
          - point-verif-workflow.qmd
          - build-verif-script.qmd
          - spatial-verif.qmd
          - plot-manipulate-spatial.qmd

format:
  html:
    theme:
      dark:
        - darkly
        - custom.scss
      light:
        - sandstone
        - custom.scss
    css: styles.css
    toc: true

editor: visual

